## Vector Stacking

Concatenating of two arrays is called vector stacking

In [1]:
import numpy as np

In [2]:
a = np.array([["New York", "Marryland"], ["Albany","annapolis"]])
b = np.array([["Ohio", "Arizona"], ["columbus","phoenix"]])

In [4]:
a

array([['New York', 'Marryland'],
       ['Albany', 'annapolis']], dtype='<U9')

In [5]:
b

array([['Ohio', 'Arizona'],
       ['columbus', 'phoenix']], dtype='<U8')

In [6]:
np.concatenate((a,b)) # axix = 0 row wise

array([['New York', 'Marryland'],
       ['Albany', 'annapolis'],
       ['Ohio', 'Arizona'],
       ['columbus', 'phoenix']], dtype='<U9')

In [7]:
np.concatenate((a,b), axis=1) # axix = 1 column wise

array([['New York', 'Marryland', 'Ohio', 'Arizona'],
       ['Albany', 'annapolis', 'columbus', 'phoenix']], dtype='<U9')

## Keep in mind things 
1. When axis = 0 then column of both the matrix should be same
2. when axix = 1 then row of both the matrix should be same

In [8]:
a = np.array([["New York", "Marryland"], ["Albany","annapolis"],["goa","banglore"]])
b = np.array([["Ohio", "Arizona"], ["columbus","phoenix"]])

In [9]:
a.shape

(3, 2)

In [13]:
a

array([['New York', 'Marryland'],
       ['Albany', 'annapolis'],
       ['goa', 'banglore']], dtype='<U9')

In [10]:
b.shape

(2, 2)

In [12]:
np.concatenate((a,b), axis = 0)

array([['New York', 'Marryland'],
       ['Albany', 'annapolis'],
       ['goa', 'banglore'],
       ['Ohio', 'Arizona'],
       ['columbus', 'phoenix']], dtype='<U9')

In [14]:
# alternative method instead of axis

np.hstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [15]:
np.vstack((a,b))

array([['New York', 'Marryland'],
       ['Albany', 'annapolis'],
       ['goa', 'banglore'],
       ['Ohio', 'Arizona'],
       ['columbus', 'phoenix']], dtype='<U9')

ArrayBroadCasting

In [17]:
c = np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
d = np.arange(6,12).reshape(2,3)
d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
print(c+d)

[[ 6  8 10]
 [12 14 16]]


In [21]:
# What if different shape

e = np.arange(6).reshape(2,3)
f = np.arange(3).reshape(1,3)

In [22]:
print(e)
print(f)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]


In [23]:
print(e + f)

[[0 2 4]
 [3 5 7]]


Array Broadcasting with rules examples 