In [ ]:
# Numpy - Numerical pyhton

In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'c:\Users\Shree\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [6]:
import numpy as np

In [9]:
lst = [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [10]:
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [11]:
# Two dimensional array
lst1 = [[1,2,3,4],[4,5,6,7]]

arr1 = np.array(lst1)
arr1

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [14]:
# Attributes: size, shape, ndim

# arr1.size
# arr1.shape
arr1.ndim

2

In [16]:
# Array with arange function

# np.arange(10)
np.arange(1,40,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.ones((3,4), dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
np.zeros((5,5), dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
np.zeros((5,5), dtype="float")

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Identity element

1. sqaure matrix
2. dig is always 1
3. other element will be zero

In [23]:
# Both identity and eye are same
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.eye(3) # identity 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
a = np.eye(3) 
a.dtype

dtype('float64')

In [ ]:
# typecasting in numply
# int32 int64- for integer
# float32

In [ ]:
# reshaping: converting from one dimension to another

In [16]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [17]:
a.shape

(6,)

In [18]:
a.ndim

1

In [19]:
a.size

6

In [20]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a.reshape(3,3)

In [21]:
# dim
# 1,1,6
# 2,3,1
# 1,3,2

# now 2 is depth
# 3 is rows
# 1 is column

a.reshape(2,3,1)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [32]:
Asian_countries = np.array(["India","Pakisthan",
                            "China","Japan","Sri Lanka",
                            "Thailand",
                           "Bangladesh","Myanmar"])
Asian_countries

array(['India', 'Pakisthan', 'China', 'Japan', 'Sri Lanka', 'Thailand',
       'Bangladesh', 'Myanmar'], dtype='<U10')

In [33]:
Asian_countries.ndim

1

In [34]:
Asian_countries.reshape(1,1,2,4,1)

array([[[[['India'],
          ['Pakisthan'],
          ['China'],
          ['Japan']],

         [['Sri Lanka'],
          ['Thailand'],
          ['Bangladesh'],
          ['Myanmar']]]]], dtype='<U10')

In [9]:
# transpose
a2 = np.arange(18).reshape(6,3)
a2


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [11]:
a2.T


array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [22]:
a

array([0, 1, 2, 3, 4, 5])

In [23]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [24]:
# Vectorization
a + 5

array([ 5,  6,  7,  8,  9, 10])

In [25]:
a2 + 5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [26]:
a2 - 5

array([[-5, -4, -3],
       [-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
a + a2

ValueError: operands could not be broadcast together with shapes (6,) (6,3) 

In [28]:
a2 / 5

array([[0. , 0.2, 0.4],
       [0.6, 0.8, 1. ],
       [1.2, 1.4, 1.6],
       [1.8, 2. , 2.2],
       [2.4, 2.6, 2.8],
       [3. , 3.2, 3.4]])

In [29]:
# randon
np.random.randint(30,100)

70

In [32]:
np.random.randint(30,130 ,(5,5))

array([[116, 109,  71, 111,  66],
       [ 57,  81, 111,  31,  47],
       [ 54, 114,  30, 103,  55],
       [ 81,  35,  70,  51,  80],
       [ 91,  79, 107,  63, 125]], dtype=int32)

In [42]:
A = np.array([[1,9],[3,7]])
B = np.array([[2,4],[6,8]])

print('A:\n', A)
print('B:\n', B)

A:
 [[1 9]
 [3 7]]
B:
 [[2 4]
 [6 8]]


In [43]:
np.dot(A,B)

array([[56, 76],
       [48, 68]])

In [45]:
# Indexing , Slicing
e = np.arange(10)
e


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
e[2]

np.int64(2)

In [47]:
e[1:5]

array([1, 2, 3, 4])

In [54]:
a1 = np.arange(30).reshape(6,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [55]:
# indexing
a1[1,4]

np.int64(9)

In [56]:
a1[3,3]

np.int64(18)

In [57]:
a1[4,1]

np.int64(21)

In [59]:
# slicing

a1[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [61]:
a1[2:4, 1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [64]:
a1[1:4:2, 1:3]

array([[ 6,  7],
       [16, 17]])

In [65]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [75]:
a1[0:6:5, 3:5]

array([[ 3,  4],
       [28, 29]])

In [ ]:
# splitting in array


In [77]:
w = np.arange(18)
w

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [79]:
# equal halfs

np.split(w, 3)

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17])]

In [87]:
o = np.arange(12)
o

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
np.split(o,4) 

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [90]:
np.split(o,[1,3,5])

[array([0]), array([1, 2]), array([3, 4]), array([ 5,  6,  7,  8,  9, 10, 11])]

In [92]:
# two dimension matrix
arr4 = np.arange(20).reshape(4,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [99]:
np.split(arr4, 2, axis = 0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [102]:
np.split(arr4, 1, axis=1)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]